name: Build and Release Extension

on:
  release:
    types: [published]

jobs:
  build-package-release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go Environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.5'

      - name: Compile Windows Binary
        working-directory: ./com.ae.discordrpc
        run: |
          # Cross-compile for Windows 64-bit
          GOOS=windows GOARCH=amd64 go build -o bin/discord-bridge.exe discord-rpc.go

      - name: Clean Source Files
        working-directory: ./com.ae.discordrpc
        run: |
          # Remove source files so they are not included in the final zip
          rm discord-rpc.go
          rm go.mod
          rm go.sum

      - name: Zip Extension
        run: |
          # Navigate into the extension folder and zip its contents
          cd com.ae.discordrpc
          zip -r ../com.ae.discordrpc.zip ./*

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: com.ae.discordrpc.zip